### PR TITLE
Regular updates

### PR DESCRIPTION
**Pull request by temisu**

### CODE REVIEW

**Comment by mywave82** [comment]
The very last commit is a bit of mixed bag :-) But except from that it looks clean

**Comment by temisu** [comment]
> The very last commit is a bit of mixed bag :-) But except from that it looks clean

Care to share why do you think it is a mixed bag? The work is still unfinished and I can still change things if you have to reason to believe I'm going to wrong direction...

**Comment by mywave82** [comment]
> > The very last commit is a bit of mixed bag :-) But except from that it looks clean
> 
> Care to share why do you think it is a mixed bag? The work is still unfinished and I can still change things if you have to reason to believe I'm going to wrong direction...

My comment was not about the code itself, just the commit.

It is ideal if each commit is one logical step - makes it easier for other people in the future that want to see what has changed. You can quickly review the commit messages and look at the changes that a
re relevant for your given use of this project.

The last commit could be split into these, or commit message atleast describe them all:
* LZH and ZIP decompressors are moved to the attic
* FreezeDecompressor, LZWDecoder PackDecompressor are added
* auto sizing compression output
* Testing is added with files that at public domain


I admire your work

**Comment by temisu** [comment]
> It is ideal if each commit is one logical step

Yeah, I was being a bit lazy here. Just working through my todo-list but I agree that 150+ files changes has gotten pretty heavy. I'll wrap it up soon and make a release as well :)

**Pull request merged**
